[package]
name = "zenlang"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.20", features = ["headers"] }
shuttle-axum = "0.32.0"
shuttle-runtime = { version = "0.32.0", default-features = false }
tokio = "1.28.2"
serde = "1.0.189"
tower-http = { version = "0.4.4", features = ["full"] }
http = "0.2.9"
zen = {git = "https://github.com/zenlang-rs/zen-lang.git", branch = "main"}
jsonwebtoken = "9.1.0"
once_cell = "1.18.0"
serde_json = "1.0.108"
shuttle-persist = "0.32.0"
mongodb = "2.0.0"
bcrypt = "0.10.1"
hyper = "0.14.27"
tower = "0.4.13"
